delete from fndapp where hostscan_guid IN (select guid from HOST_SCAN where vne_id not in (select vne_id from vne))
delete from fndappvuln where hostscan_guid IN (select guid from HOST_SCAN where vne_id not in (select vne_id from vne))
delete from HOST_SCAN where vne_id not in (select vne_id from vne)
delete from HOST where vne_id not in (select vne_id from vne)
delete from AUDIT_TBL where vne_id not in (select vne_id from vne)
delete from AUDIT_IMPORT_FAILURE where vne_id not in (select vne_id from vne)
delete from SCAN_PROFILE where vne_id not in (select vne_id from vne)
delete from SIH_EXEC_SUMMARY_GROUP where vne_id not in (select vne_id from vne)
delete from VULNERABILITY where vne_id not in (select vne_id from vne)
delete from sih_group_all_members where group_member_id IN (select id from sih_group_member where vne_id not in (select vne_id from vne))
delete from sih_group_member where vne_id not in (select vne_id from vne)
delete from DATA_UPLOAD_SOURCES where vne_id not in (select vne_id from vne)
delete from DEVICE_PROFILER where vne_id not in (select vne_id from vne)
delete from SIH_IDENTITY_VNE_N_ACCESS where vne_id not in (select vne_id from vne)
delete from SIH_IDENTITY_VNE_NG_ACCESS where vne_id not in (select vne_id from vne)
delete from NETWORK where vne_id not in (select vne_id from vne)
delete from NETWORK_GROUP where vne_id not in (select vne_id from vne)
delete from NETWORK_GROUP_NETWORK where vne_id not in (select vne_id from vne)
delete from NETWORK_LIST where vne_id not in (select vne_id from vne)
delete from OS where vne_id not in (select vne_id from vne)
delete from OS_GROUP where vne_id not in (select vne_id from vne)
delete from OS_GROUP_OS where vne_id not in (select vne_id from vne)
delete from APPLICATION where vne_id not in (select vne_id from vne)
delete from SUMMARY_OS where vne_id not in (select vne_id from vne)
delete from SUMMARY_TOPN_APPS where vne_id not in (select vne_id from vne)
delete from SUMMARY_TOPN_RISKAPPS where vne_id not in (select vne_id from vne)
delete from SUMMARY_TOPN_SANS where vne_id not in (select vne_id from vne)
delete from SUMMARY_TOPN_VULNS where vne_id not in (select vne_id from vne)
delete from SUMMARY where vne_id not in (select vne_id from vne)
